<?php
/**
 * Vm2Mage
 *
 * @author Yireo
 * @package Vm2Mage
 * @copyright Copyright 2011
 * @license Open Source License
 * @link http://www.yireo.com
 */
?>

<div class="content-header">
<table cellspacing="0">
	<tr>
		<td style="width:100%;"><h3 class="icon-head head-tag"><?php echo $this->getHeader('System Check'); ?></h3></td>
	</tr>
</table>
</div>
    
<?php foreach($this->getChecks() as $group => $checks) { ?>
<?php if($group == 'conf') $title = 'Magento Configuration';  ?>
<?php if($group == 'system') $title = 'Hosting Requirements';  ?>
<?php if($group == 'stats') $title = 'Statistics';  ?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__($title); ?></h4>
    </div>

    <div class="fieldset ">
        <table cellspacing="5" class="form-list">
            <?php foreach($checks as $check) { ?>
            <tr>
                <td width="150"><strong><?php echo $check['check']; ?></strong></td>
                <td width="50"><img src="<?php echo $this->getSkinUrl('images/vm2mage/check-'.$check['status'].'.png'); ?>" title="<?php echo $check['status']; ?>" alt="<?php echo $check['status']; ?>" /></td>
                <td><?php echo $check['description']; ?></td>
            </tr>
            <?php } ?>
        </table>
    </div>
</div>
<?php } ?>

<strong>Legend:</strong><br/>
<img src="<?php echo $this->getSkinUrl('images/vm2mage/check-ok.png'); ?>" />&nbsp;<?php echo $this->__('Everything is ok'); ?><br/>
<img src="<?php echo $this->getSkinUrl('images/vm2mage/check-warning.png'); ?>" />&nbsp;<?php echo $this->__('There might be something wrong, so be warned'); ?><br/>
<img src="<?php echo $this->getSkinUrl('images/vm2mage/check-error.png'); ?>" />&nbsp;<?php echo $this->__('Something is preventing Vm2Mage from functioning correctly'); ?><br/>

